# Generated by Django 5.1.1 on 2024-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userprofile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
