# Generated by Django 5.1.1 on 2024-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userprofile_two_factor_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reset_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
